services:
  - type: web
    name: domain-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python health_server.py
    envVars:
      - key: 7k7C7n7aY8Ot7P8D838c8X9O9E6uB7S7Ip8j8R7u6i8F
        sync: false
      - key: PORKBUN_API_KEY
        sync: false
      - key: PORKBUN_SECRET_KEY
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    autoDeploy: true
